### PR TITLE
SL7 update

### PR DESCRIPTION
**Pull request by tofu-rocketry**
Update the GH pages to point to the SL7 version properly and do some minor tidying and updating.

### CODE REVIEW

**Comment by gregcorbett** [comment]
looks okay, do you know of a way to see the rendered page(s) of the branch with the changes?

**Comment by tofu-rocketry** [comment]
Not online as far as I know. It can be done locally - see https://jekyllrb.com/docs/home/ if you're interested, but don't worry about it as I have run it locally.

Just trying to fix the build at the moment.

**Comment by tofu-rocketry** [comment]
Build fixed in #13. Will rebase on that once it's merged.

**Comment by tofu-rocketry** [comment]
I realise that the page generation has borked somehow with the last PR, but could you still have a look at this PR?

**Pull request merged**
